#include <stdio.h>

#if defined(_WIN32)
#include <Windows.h>
#endif

#include <string.h>
#include <stdlib.h>


static const char *default_translate_data[] = {
	"************** WARNING: NOT Running as Admin/Root **************@************** AVERTISSEMENT: ne fonctionne pas en tant qu'administrateur / racine **************",
	"Active@Actif",
	"Allocation Failed@Échec de l'allocation",
	"automatically attempt to register sightings with MISP server@tenter automatiquement d'enregistrer les observations auprès du serveur MISP",
	"Begin Module Import@Commencer l’importation du module",
	"bit flags for basic (0), meta (1), string matches (2), tags (4)@Octet d’indication pour basic (0), meta (1), correspondances de chaînes (2), tags (4)",
	"Checking IP@Vérification IP",
	"CMD Hit@CMD indicateur",
	"Compiled rules file corrupt@Fichier compilé corrompu",
	"Completed Upload of Detected Samples@Téléchargement des échantillons détectés terminés",
	"Could not allocate scan results data@Impossible d'allouer les données de résultats de l’analyse",
	"Could not attach to process@Impossible de joindre au processus",
	"Could not create thread!@Impossible de créer la séquence!",
	"Could not define external variable is_filescan to@Impossible de définir la variable externe is_filescan sur",
	"Could not initialize curl for signature file download@Impossible d'initialiser la boucle pour le téléchargement du fichier de signature",
	"Could not initialize curl for upload of file@Impossible d'initialiser la boucle pour le téléchargement du fichier",
	"Could not initialize curl for upload of hit result@Impossible d'initialiser la boucle pour le téléchargement du résultat de hit",
	"Could not initialize curl for upload of results file@Impossible d'initialiser la boucle pour le téléchargement du fichier de résultats",
	"Could not open file@Impossible d'ouvrir le fichier",
	"Could not open signature file for download.@Impossible d'ouvrir le fichier de signature à télécharger.",
	"CPU throttling number of MICROSECONDS to sleep between file scans@La limitation du processeur en MICROSECONDS pour dormir entre les analyses de fichiers",
	"Detail File Hit@Détail du fichier atteint",
	"Detected Files Warning@Avertissement des fichiers détectés",
	"Development Signatures Mode Active@Mode de signature de développement Active",
	"Directories Skipped@Répertoires ignorés",
	"Directory Access Denied@Accès à l'annuaire refusé",
	"DirList Values@Valeurs DirList",
	"dirlist.txt data ignored@données dirlist.txt ignorées",
	"display the tool and yara version and exit@afficher l'outil, la version yara et quitter",
	"DNS Buffer@Tampon DNS",
	"DNS Buffered@Tampon DNS",
	"DNS Hit@DNS Hit",
	"DNS List Interrupted@Liste DNS interrompue",
	"DNS Scan@DNS Scan",
	"DNS Signature Items Loaded@Les signatures DNS sont chargés",
	"Download error occurred for signature file@Une erreur de téléchargement s'est produite pour le fichier de signature",
	"download new set of rules and signatures then exit@Téléchargez un nouvel ensemble de règles et de signatures puis quittez",
	"Downloading rules and signature files@Téléchargement des règles et les fichiers de signatures",
	"End@Fin",
	"Endpoint Scanner Version@Version de l’outils EPST",
	"Environment Variables@Variables du système",
	"EOF Not Reached@EOF non atteint",
	"EPST File Scan@Vérifications complété par l’EPST",
	"Error: dirlist memory allocation failed!@Erreur: l'allocation de la mémoire pour la liste de lecture a échoué!",
	"Event Details Exceeded Buffer@La mémoire tampon est pleine",
	"Event Hits Warning@Avertissement d’activités suspecte",
	"Event ID Found Stats@Activités d’identification statistique",
	"Event ID Signature Items Loaded@Activités d’identification d’activités chargés",
	"Event Log Buffer@Activités tampon du journal des activités",
	"Event Log Enumerate List Interrupted@Journal des activités interrompue",
	"Event Log Enumerate List@Journal des activités",
	"Event Log Query Interrupted@Requête du journal des activités interrompue",
	"Event Log Query Parse@Analyser la requête du journal des activités",
	"Event Log Scan@Analyse du journal des activités",
	"Event Scan@Analyse des activités",
	"Event Signature Alloc Failed@L'allocation de signature d'activités a échoué",
	"EVT Hit@EVT Hit",
	"Excluded@Exclu",
	"Executable folder not added to exclude directory list!@Dossier exécutable non ajouté pour exclure la liste des répertoires!",
	"Existing file could not be renamed as a backup.@Le fichier existant n'a pas pu être renommé en tant que sauvegarde.",
	"ExpandEnvironmentStrings error occurred@Une erreur ExpandEnvironmentStrings s'est produite",
	"ExpandEnvironmentStrings exceeded buffer size!@ExpandEnvironmentStrings a dépassé la taille de la mémoire tampon!",
	"Experimental Development Signatures Mode Active@Mode de signature experimental est actif",
	"Experimental Mode Active@Mode expérimental actif",
	"Experimental Signatures Mode Active@Mode de signatures expérimentales actif",
	"Failed@Échoué",
	"FALSE@FAUX",
	"fast matching mode@mode de correspondance rapide",
	"File could not be removed.@Le fichier n'a pas pu être supprimé.",
	"File Data Buffer@Ficher en memoire tampon",
	"File does not exist for upload@Le fichier n'existe pas pour le téléchargement en amont",
	"File Scan Complete@Analyse de fichiers terminée",
	"File Scan@Analyse de fichiers",
	"Filename Signature Items Loaded@Éléments de signature de nom de fichier chargés",
	"Filenames Scan@Filenames Scan",
	"Filepath strdup error@Erreur de chemin du fichier strdup",
	"Files Skipped@Fichiers ignorés",
	"Finalizing Threads@Finalisation des séquences",
	"Finished Endpoint Scan@Analyse complété par l’outil EPST",
	"Finished File Scan@Analyse de fichiers terminée",
	"Finished Process Scan@Analyse de processus terminée",
	"Finished System Scan@Analyse système terminée",
	"Finished@Fini",
	"force scanning to complete after max number of SECONDS@L’analyse forcée complété après SECONDS maximum",
	"Found Out of Range Event ID:@L’activité d’identification est hors de portée",
	"Get Process IDs@Obtenir les identifications",
	"Hash could not be calculated for results file@Le hachage n'a pas pu être calculé pour le fichier de résultats",
	"hash files and check master MD5, SHA1, SHA256 hit lists@Le hachage des fichiers et la validation des listes de résultats principales MD5, SHA1, SHA256",
	"Hash scan could not allocate file data@L’outil de hachage n'a pas pu allouer les données de fichier",
	"Hash scan could not read file@Loutil de hachage n'a pas pu lire le fichier",
	"Hash Scan@L’outil de hachage",
	"HIT@Hit",
	"Important Files (Rules, Signatures, Trace, Results):@Fichiers importants (règles, signatures, trace, résultats):",
	"Internal Error@Erreur interne",
	"Invalid arguments for hash function (md5, sha1, sha256 or checksum32)@Arguments non valides pour la fonction de hachage (md5, sha1, sha256 ou checksum32)",
	"Invalid external variable type@Type de variable externe non valide",
	"IP Address Scan@Scan d'adresse IP",
	"IP Hit@IP Hit",
	"IP Signature Items Loaded@Éléments de signature IP chargés",
	"level of extra details in the trace (0,1,2,3)@niveau de détails supplémentaires dans la compilation (0,1,2,3)",
	"Loading compiled Yara rule file@Chargement du fichier des règles Yara est compilé",
	"Maximum number of threads is@Le nombre maximum de threads est",
	"MD5 Signature Items Loaded@Éléments de signature MD5 chargés",
	"MUTANT Hit@MUTANT Hit",
	"Mutex Scan@Mutex Scan",
	"Mutex Signature Items Loaded@Articles de signature Mutex chargés",
	"No API Key available for scan results upload.@Aucune clé API disponible pour le téléchargement des résultats de l'analyse.",
	"No API Key available for trace file upload.@Aucune clé API disponible pour le téléchargement du fichier de trace.",
	"No API Key available for upload.@Aucune clé API disponible pour le téléchargement.",
	"No Log Files Found@Aucun fichier journal trouvé",
	"None Found@Rien trouvé",
	"Not Active@Pas actif",
	"Not Allocated@Pas alloué",
	"Not Running as Admin: Skipping Event Log Scan@Compte administrateur non sélectionné: ignorer l'analyse du journal des événements",
	"Not Running as Admin: Skipping Process Scan@Compte administrateur non sélectionné: ignorer l'analyse de processus",
	"NOT Running as User Admin@Compte administrateur non sélectionné",
	"number of SECONDS before a file or process scan times out@Nombre de SECONDS requis avant l'expiration d'un fichier ou d'un processus",
	"Old backup could not be removed.@Sauvegarde d’archive n’a pas pu être supprimée.",
	"Old version of file could not be removed.@L'ancienne version du fichier n'a pas pu être supprimée.",
	"Open DNS List@Ouvrir la liste DNS",
	"Open Failed@Échec d'ouverture",
	"Open Socket List@Ouvrir la liste des sockets",
	"Out of memory@Mémoire insuffisante",
	"Output Data@Des données de sortie(output)",
	"Output Search Signatures@Signatures de recherche de sortie(output)",
	"per file max NUMBER of matching rules to record@NOMBRE maximum de règles correspondantes pour un ficher",
	"PID@PID",
	"Pipe Open Failed@Échec d’ouverture",
	"Please manually restore from backup or try again later.@Veuillez restaurer manuellement à partir de la sauvegarde ou réessayer plus tard.",
	"Process Identification Interrupted@Activité Identification interrompue",
	"Process IDs Found@Activité Identification trouvée",
	"Process IDs@Activité Identification",
	"Process List@Liste des activités",
	"Process Memory Scan@Activité d’analyse de la mémoire vive",
	"Processing@En traitement",
	"Query Enumerate Event Logs@Énumération de la liste d’évenements ",
	"Read File Data Size Difference@Lire la différence de taille des données de fichier",
	"Read File Data Warning@Lire les données de l'avertissement",
	"Read File Header Warning@Lire l'en-tête de l'avertissement de fichier",
	"Register Keys Signature Items Loaded@Enregistrer les éléments de signature des clés chargés",
	"Registry Hit@Activité trouvé dans le registre",
	"Registry Keys Scan@Analyse des clés de registre",
	"Registry Scan@Analyse du registre",
	"regrun environment variable is@la variable d'environnement regrun est",
	"Results file does not exist for upload@Le fichier de résultats n'existe pas pour le téléchargement",
	"Results File Hash@Fichier de résultats Hash",
	"Results File@Fichier de résultats",
	"Rules compiled with wrong version@Règles compilées avec une mauvaise version",
	"Running as User Admin@Exécution en tant qu'administrateur utilisateur",
	"scan active sockets and dns cache for IPs in hit list@analyser les sockets actifs et le cache DNS pour les IP dans la liste de résultats",
	"scan directory tree for file names in hit list@analyser l'arborescence des répertoires pour les noms de fichiers dans la liste de résultats",
	"Scan Event Log@Journal des activités",
	"scan event logs and command output for specific events@Analyser les journaux d'activités et les sorties de commande pour des activités spécifiques",
	"Scan Event Logs@Analyser les journaux d'activités",
	"Scan file upload failed@Échec du téléchargement du fichier d'analyse",
	"scan files with yara rules@analyser les fichiers avec les règles yara",
	"Scan hit value upload failed@Le téléchargement de la valeur de hit a échoué",
	"scan memory of all active processes with Yara rules@analyser la mémoire de tous les processus actifs avec les règles Yara",
	"scan mutex items for keys in hit list@analyser les éléments mutex pour rechercher les clés dans la liste de résultats",
	"Scan report upload failed@Échec du téléchargement du rapport d'analyse",
	"scan the URL cache for items in the hit list@analysez le cache URL pour les éléments de la liste de résultats",
	"scan the DNS cache for items in the hit list@analysez le cache DNS pour les éléments de la liste de résultats",
	"scan the registry for keys in hit list@rechercher dans le registre les clés de la liste de résultats",
	"Scanned Directory@Balayage du répertoire",
	"Scanned@Le balayage",
	"Scanning timed out@Le balayage a expiré",
	"set maximum stack size (default=16384)@définir la taille maximale de la pile (par défaut = 16384)",
	"SHA1 Signature Items Loaded@Éléments de signature SHA1 chargés",
	"SHA256 Signature Items Loaded@Éléments de signature SHA256 chargés ",
	"show this help and exit@afficher l’aide et quitter",
	"Sighting@Observation",
	"Signature List Read Realloc Failed - continuing@Échec de la ré-allocation de la liste de signatures - continuer",
	"Skipping Directory@Ignorer le répertoire",
	"Skipping Path Too Long@Ignorer ficher trop long",
	"Skipping Symbolic Link@Ignorez le lien symbolique",
	"Skipping Yara Rules File@Ignorez le fichier de règles Yara",
	"Socket Identification Interrupted@Socket Identification interrompu",
	"Socket Scan@Socket Scan",
	"specify folder name for downloaded and generated files@spécifiez le nom du dossier pour les fichiers téléchargés et générés",
	"specify name for a compiled Yara rules file@spécifiez le nom d'un fichier de règles Yara compilé",
	"specify NUMBER of threads to use for scanning files@spécifier le NOMBRE de threads à utiliser pour analyser les fichiers",
	"Stack overflow evaluating condition@Stack overflow evaluation des conditions",
	"Start@Début",
	"Started@Commencé",
	"Starting Endpoint Scan@Démarrage de l’outil EPST",
	"Starting System Scan@Démarrage du system de balayage",
	"suppress default upload of hit samples to MISP server@supprimer le téléchargement par défaut des échantillons de résultats sur le serveur MISP",
	"suppress default upload of results to MISP server@supprimer le téléchargement par défaut des résultats sur le serveur MISP",
	"SysCmds Scan@SysCmds Balayage",
	"System Command Items Loaded@Commandes du système chargés",
	"System Command Not Executed@Commandes du système non exécutée",
	"System Command Signature Items Loaded@Commandes du système: Éléments de signature chargés",
	"System Command Start@Commandes du système pour commencer",
	"System Command@Commandes du système",
	"System Commands to Run@Commandes du système pour exécuter",
	"System Config Interrupted@System Config Interrupted",
	"System Config@System Config",
	"Terminating Program@Conclusion du programme",
	"Thread@Thread",
	"Threaded Processing@En traitement",
	"Threading Queue Initialization Failed!@Échec de l'initialisation de la file d'attente!",
	"Timed Out@Fin du temps alloué”",
	"Timed Out@Fin du temps alloué",
	"End Point Scanning Tool uses signature data and Yara rules@L'outil d'analyse de point final utilise les données de signature et les règles Yara",
	"to check files, processes and system resources for malware.@pour vérifier les fichiers, les processus et les ressources système pour les logiciels malveillants.",
	"Trace File Warning@Avertissement de fichier de trace",
	"trace to file (1), trace to stdout (2) both (3)@Trace vers le fichier (1), trace vers stdout (2) both (3)",
	"TRUE@VRAI",
	"Truncating@Truncating",
	"turn on explicit scan mode so all are off by default@Activer le mode d’analyse explicite pour que tous soient désactivés par défaut",
	"Unknown Hive Name for registry key@Nom de fiché mère inconnu pour la clé de registre",
	"Upload Detected Files Read Warning@Télécharger les fichiers détectés, lire l'avertissement",
	"upload existing results file then exit@Télécharger le fichier de résultats existant puis quitter",
	"Uploading Detected Samples@Téléchargement en amont d'échantillons détectés",
	"Uploading results JSON file.@Téléchargement du fichier JSON des résultats.",
	"Uploading results JSON file@Téléchargement des résultats du fichier JSON",
	"Uploading results trace file.@Téléchargement du fichier de suivi des résultats.",
	"URL failed@L'URL a échoué",
	"use development vs normal yara rules@utiliser le développement vs les règles normales de yara",
	"use experimental vs normal yara rules (same filename, different download)@Utilisation de règles yara expérimentales vs normales (même nom de fichier, téléchargement différent)",
	"use local rules and signature files already downloaded@Utiliser les règles locales et les fichiers de signatures déjà téléchargés",
	"Using Packaged Cert@Utilisation de Packaged Cert",
	"Validated Event Signatures@Signatures d'activités validées",
	"Validated Regex Signatures@Signatures Regex validées",
	"WARNING: Another EPST may be running. Skipping@AVERTISSEMENT: EPST est présentement ouvert dans un autre fenêtre. Ignorer",
	"WARNING: Check Expanded DirList Item@AVERTISSEMENT: Vérifiez l'élément DirList",
	"Warning: Could not read header for EPST Rules File Check@AVERTISSEMENT: Impossible de lire l'en-tête pour la vérification du fichier de règles EPST",
	"WARNING: DNS Regex Search Result Out of Bounds@AVERTISSEMENT: Résultat de recherche DNS Regex hors limites",
	"Warning: Header Mismatch for EPST Rules File Check@AVERTISSEMENT: incompatibilité avec l’outil EPST",
	"Yara Development Mode Active@Mode de développement Yara Actif",
	"Yara Initialization Code@Code d’initialization Yara",
	"YARA Library Version@Version de YARA",
	"Yara rule file is invalid or not compiled@Le fichier des règles Yara n'est pas valide ou n'est pas compilé",
	"Yara Rule Scanning@Analyse des règles Yara",
	NULL
};

int split_add_translate_data_line(char *line);

int use_default_translate_data() {
	int i = 0;
	const char *s;
	char buf[2048 + 1];

	while ((s = default_translate_data[i]) != NULL) {
		// Copy const string into buffer for the split
		strncpy(buf, s, 2048);
		buf[2048] = '\0';
		split_add_translate_data_line(buf);
		i++;
	}

	return i;
}